# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(301, 343)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 301, 331))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.enrollButton = QtWidgets.QPushButton(self.page_main)
        self.enrollButton.setGeometry(QtCore.QRect(50, 60, 201, 41))
        self.enrollButton.setObjectName("enrollButton")
        self.memorizeButton = QtWidgets.QPushButton(self.page_main)
        self.memorizeButton.setGeometry(QtCore.QRect(50, 110, 201, 41))
        self.memorizeButton.setObjectName("memorizeButton")
        self.gameButton = QtWidgets.QPushButton(self.page_main)
        self.gameButton.setGeometry(QtCore.QRect(50, 160, 201, 41))
        self.gameButton.setObjectName("gameButton")
        self.recordButton = QtWidgets.QPushButton(self.page_main)
        self.recordButton.setGeometry(QtCore.QRect(50, 210, 201, 41))
        self.recordButton.setObjectName("recordButton")
        self.stackedWidget.addWidget(self.page_main)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 261, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.enterButton_1 = QtWidgets.QPushButton(self.page_2)
        self.enterButton_1.setGeometry(QtCore.QRect(230, 230, 51, 71))
        self.enterButton_1.setObjectName("enterButton_1")
        self.KorEdit = QtWidgets.QLineEdit(self.page_2)
        self.KorEdit.setGeometry(QtCore.QRect(20, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(16)
        self.KorEdit.setFont(font)
        self.KorEdit.setObjectName("KorEdit")
        self.EngEdit = QtWidgets.QLineEdit(self.page_2)
        self.EngEdit.setGeometry(QtCore.QRect(20, 230, 201, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(16)
        self.EngEdit.setFont(font)
        self.EngEdit.setObjectName("EngEdit")
        self.backButton_1 = QtWidgets.QPushButton(self.page_2)
        self.backButton_1.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backButton_1.setObjectName("backButton_1")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(110, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_9.setGeometry(QtCore.QRect(60, 80, 181, 151))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.next_2 = QtWidgets.QPushButton(self.page_3)
        self.next_2.setGeometry(QtCore.QRect(250, 240, 31, 31))
        self.next_2.setObjectName("next_2")
        self.prev_2 = QtWidgets.QPushButton(self.page_3)
        self.prev_2.setGeometry(QtCore.QRect(20, 240, 31, 31))
        self.prev_2.setObjectName("prev_2")
        self.backButton_2 = QtWidgets.QPushButton(self.page_3)
        self.backButton_2.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backButton_2.setObjectName("backButton_2")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(100, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.score = QtWidgets.QLabel(self.page)
        self.score.setGeometry(QtCore.QRect(190, 40, 56, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.score.setFont(font)
        self.score.setObjectName("score")
        self.enterButton_3 = QtWidgets.QPushButton(self.page)
        self.enterButton_3.setGeometry(QtCore.QRect(220, 280, 61, 31))
        self.enterButton_3.setObjectName("enterButton_3")
        self.answerEdit = QtWidgets.QLineEdit(self.page)
        self.answerEdit.setGeometry(QtCore.QRect(20, 280, 191, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(16)
        self.answerEdit.setFont(font)
        self.answerEdit.setObjectName("answerEdit")
        self.prev_3 = QtWidgets.QPushButton(self.page)
        self.prev_3.setGeometry(QtCore.QRect(20, 240, 31, 31))
        self.prev_3.setObjectName("prev_3")
        self.pushButton_14 = QtWidgets.QPushButton(self.page)
        self.pushButton_14.setGeometry(QtCore.QRect(60, 80, 181, 151))
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(110, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.next_3 = QtWidgets.QPushButton(self.page)
        self.next_3.setGeometry(QtCore.QRect(250, 240, 31, 31))
        self.next_3.setObjectName("next_3")
        self.backButton_3 = QtWidgets.QPushButton(self.page)
        self.backButton_3.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backButton_3.setObjectName("backButton_3")
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enrollButton.setText(_translate("MainWindow", "등록하기"))
        self.memorizeButton.setText(_translate("MainWindow", "외우기"))
        self.gameButton.setText(_translate("MainWindow", "게임하기"))
        self.recordButton.setText(_translate("MainWindow", "기록보기"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "English"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Korean"))
        self.enterButton_1.setText(_translate("MainWindow", "enter"))
        self.KorEdit.setText(_translate("MainWindow", "Korean"))
        self.EngEdit.setText(_translate("MainWindow", "English"))
        self.backButton_1.setText(_translate("MainWindow", "<-"))
        self.label_4.setText(_translate("MainWindow", "000/000"))
        self.next_2.setText(_translate("MainWindow", ">"))
        self.prev_2.setText(_translate("MainWindow", "<"))
        self.backButton_2.setText(_translate("MainWindow", "<-"))
        self.label.setText(_translate("MainWindow", "SCORE :"))
        self.score.setText(_translate("MainWindow", "0"))
        self.enterButton_3.setText(_translate("MainWindow", "enter"))
        self.prev_3.setText(_translate("MainWindow", "<"))
        self.label_5.setText(_translate("MainWindow", "000/000"))
        self.next_3.setText(_translate("MainWindow", ">"))
        self.backButton_3.setText(_translate("MainWindow", "<-"))

import resources_rc
