# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(301, 343)
        MainWindow.setStyleSheet("background-image:")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 301, 321))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.enrollButton = QtWidgets.QPushButton(self.page_main)
        self.enrollButton.setGeometry(QtCore.QRect(50, 60, 201, 41))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(11)
        self.enrollButton.setFont(font)
        self.enrollButton.setObjectName("enrollButton")
        self.memorizeButton = QtWidgets.QPushButton(self.page_main)
        self.memorizeButton.setGeometry(QtCore.QRect(50, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(11)
        self.memorizeButton.setFont(font)
        self.memorizeButton.setObjectName("memorizeButton")
        self.gameButton = QtWidgets.QPushButton(self.page_main)
        self.gameButton.setGeometry(QtCore.QRect(50, 160, 201, 41))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(11)
        self.gameButton.setFont(font)
        self.gameButton.setObjectName("gameButton")
        self.recordButton = QtWidgets.QPushButton(self.page_main)
        self.recordButton.setGeometry(QtCore.QRect(50, 210, 201, 41))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(11)
        self.recordButton.setFont(font)
        self.recordButton.setObjectName("recordButton")
        self.stackedWidget.addWidget(self.page_main)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 261, 161))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(120)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.enterButton_1 = QtWidgets.QPushButton(self.page_2)
        self.enterButton_1.setGeometry(QtCore.QRect(230, 230, 51, 71))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        self.enterButton_1.setFont(font)
        self.enterButton_1.setObjectName("enterButton_1")
        self.KorEdit = QtWidgets.QLineEdit(self.page_2)
        self.KorEdit.setGeometry(QtCore.QRect(20, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        self.KorEdit.setFont(font)
        self.KorEdit.setStyleSheet("color:rgb(80, 80, 80)")
        self.KorEdit.setMaxLength(20)
        self.KorEdit.setObjectName("KorEdit")
        self.EngEdit = QtWidgets.QLineEdit(self.page_2)
        self.EngEdit.setGeometry(QtCore.QRect(20, 230, 201, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        self.EngEdit.setFont(font)
        self.EngEdit.setStyleSheet("color:rgb(80, 80, 80)")
        self.EngEdit.setMaxLength(20)
        self.EngEdit.setObjectName("EngEdit")
        self.backButton_1 = QtWidgets.QPushButton(self.page_2)
        self.backButton_1.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("굴림")
        font.setPointSize(9)
        self.backButton_1.setFont(font)
        self.backButton_1.setObjectName("backButton_1")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.status_2 = QtWidgets.QLabel(self.page_3)
        self.status_2.setGeometry(QtCore.QRect(110, 270, 91, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(16)
        self.status_2.setFont(font)
        self.status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.status_2.setObjectName("status_2")
        self.wordScreen_2 = QtWidgets.QPushButton(self.page_3)
        self.wordScreen_2.setGeometry(QtCore.QRect(20, 60, 261, 171))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(18)
        self.wordScreen_2.setFont(font)
        self.wordScreen_2.setText("")
        self.wordScreen_2.setObjectName("wordScreen_2")
        self.next_2 = QtWidgets.QPushButton(self.page_3)
        self.next_2.setGeometry(QtCore.QRect(250, 270, 31, 31))
        self.next_2.setObjectName("next_2")
        self.prev_2 = QtWidgets.QPushButton(self.page_3)
        self.prev_2.setGeometry(QtCore.QRect(20, 270, 31, 31))
        self.prev_2.setObjectName("prev_2")
        self.backButton_2 = QtWidgets.QPushButton(self.page_3)
        self.backButton_2.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backButton_2.setObjectName("backButton_2")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.score = QtWidgets.QLabel(self.page)
        self.score.setGeometry(QtCore.QRect(80, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.score.setFont(font)
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("score")
        self.enterButton_3 = QtWidgets.QPushButton(self.page)
        self.enterButton_3.setGeometry(QtCore.QRect(220, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        self.enterButton_3.setFont(font)
        self.enterButton_3.setObjectName("enterButton_3")
        self.answerEdit = QtWidgets.QLineEdit(self.page)
        self.answerEdit.setGeometry(QtCore.QRect(20, 270, 191, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        self.answerEdit.setFont(font)
        self.answerEdit.setObjectName("answerEdit")
        self.wordScreen_3 = QtWidgets.QPushButton(self.page)
        self.wordScreen_3.setGeometry(QtCore.QRect(20, 90, 261, 171))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(18)
        self.wordScreen_3.setFont(font)
        self.wordScreen_3.setText("")
        self.wordScreen_3.setObjectName("wordScreen_3")
        self.status_3 = QtWidgets.QLabel(self.page)
        self.status_3.setGeometry(QtCore.QRect(170, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("돋움")
        font.setPointSize(12)
        self.status_3.setFont(font)
        self.status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.status_3.setObjectName("status_3")
        self.backButton_3 = QtWidgets.QPushButton(self.page)
        self.backButton_3.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.backButton_3.setObjectName("backButton_3")
        self.combo = QtWidgets.QPushButton(self.page)
        self.combo.setGeometry(QtCore.QRect(210, 10, 77, 75))
        self.combo.setStyleSheet("QPushButton{\n"
"background:transparent\n"
"}\n"
"QPushButton:checked{\n"
"background-image:url(:/img/face.png)}")
        self.combo.setText("")
        self.combo.setCheckable(True)
        self.combo.setChecked(False)
        self.combo.setAutoExclusive(False)
        self.combo.setObjectName("combo")
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enrollButton.setText(_translate("MainWindow", "등록하기"))
        self.memorizeButton.setText(_translate("MainWindow", "외우기"))
        self.gameButton.setText(_translate("MainWindow", "게임하기"))
        self.recordButton.setText(_translate("MainWindow", "기록보기"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "English"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Korean"))
        self.enterButton_1.setText(_translate("MainWindow", "enter"))
        self.KorEdit.setText(_translate("MainWindow", "Korean"))
        self.EngEdit.setText(_translate("MainWindow", "English"))
        self.backButton_1.setText(_translate("MainWindow", "<-"))
        self.status_2.setText(_translate("MainWindow", "00/00"))
        self.next_2.setText(_translate("MainWindow", ">"))
        self.prev_2.setText(_translate("MainWindow", "<"))
        self.backButton_2.setText(_translate("MainWindow", "<-"))
        self.score.setText(_translate("MainWindow", "00000"))
        self.enterButton_3.setText(_translate("MainWindow", "enter"))
        self.status_3.setText(_translate("MainWindow", "(00/00)"))
        self.backButton_3.setText(_translate("MainWindow", "<-"))

import resources_rc
